#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_AdopcionWS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MyWSDB")]
	public partial class DataClassesWSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertWScontacto(WScontacto instance);
    partial void UpdateWScontacto(WScontacto instance);
    partial void DeleteWScontacto(WScontacto instance);
    partial void InsertSolicitudesAdopcionWS(SolicitudesAdopcionWS instance);
    partial void UpdateSolicitudesAdopcionWS(SolicitudesAdopcionWS instance);
    partial void DeleteSolicitudesAdopcionWS(SolicitudesAdopcionWS instance);
    #endregion
		
		public DataClassesWSDataContext() : 
				base(global::Data_AdopcionWS.Properties.Settings.Default.MyWSDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesWSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesWSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesWSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesWSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<WScontacto> WScontacto
		{
			get
			{
				return this.GetTable<WScontacto>();
			}
		}
		
		public System.Data.Linq.Table<SolicitudesAdopcionWS> SolicitudesAdopcionWS
		{
			get
			{
				return this.GetTable<SolicitudesAdopcionWS>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WScontacto")]
	public partial class WScontacto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_cont;
		
		private string _nombre;
		
		private string _correo;
		
		private string _descripcion;
		
		private System.DateTime _fecha;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_contChanging(int value);
    partial void OnId_contChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnfechaChanging(System.DateTime value);
    partial void OnfechaChanged();
    #endregion
		
		public WScontacto()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_cont", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_cont
		{
			get
			{
				return this._Id_cont;
			}
			set
			{
				if ((this._Id_cont != value))
				{
					this.OnId_contChanging(value);
					this.SendPropertyChanging();
					this._Id_cont = value;
					this.SendPropertyChanged("Id_cont");
					this.OnId_contChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(500)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SolicitudesAdopcionWS")]
	public partial class SolicitudesAdopcionWS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id_SolicitudWS;
		
		private int _Id_Usuario;
		
		private int _Id_Animal;
		
		private System.Nullable<System.DateTime> _FechaSolicitud;
		
		private System.Nullable<int> _EdadSolicitante;
		
		private string _Ocupacion;
		
		private string _DireccionCompleta;
		
		private string _Telefono;
		
		private string _RedesSociales;
		
		private string _TipoVivienda;
		
		private string _TenenciaInmueble;
		
		private string _PermisoDuenio;
		
		private string _SeguridadEntorno;
		
		private string _IntegrantesHogar;
		
		private string _AcuerdoFamiliar;
		
		private string _HayAlergias;
		
		private string _OtrasMascotas;
		
		private string _SociabilidadMascotas;
		
		private string _HorasSolo;
		
		private string _LugarDormir;
		
		private string _PlanMudanza;
		
		private string _MotivoAdopcion;
		
		private bool _AceptaGastos;
		
		private bool _AceptaCompromiso;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_SolicitudWSChanging(string value);
    partial void OnId_SolicitudWSChanged();
    partial void OnId_UsuarioChanging(int value);
    partial void OnId_UsuarioChanged();
    partial void OnId_AnimalChanging(int value);
    partial void OnId_AnimalChanged();
    partial void OnFechaSolicitudChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaSolicitudChanged();
    partial void OnEdadSolicitanteChanging(System.Nullable<int> value);
    partial void OnEdadSolicitanteChanged();
    partial void OnOcupacionChanging(string value);
    partial void OnOcupacionChanged();
    partial void OnDireccionCompletaChanging(string value);
    partial void OnDireccionCompletaChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnRedesSocialesChanging(string value);
    partial void OnRedesSocialesChanged();
    partial void OnTipoViviendaChanging(string value);
    partial void OnTipoViviendaChanged();
    partial void OnTenenciaInmuebleChanging(string value);
    partial void OnTenenciaInmuebleChanged();
    partial void OnPermisoDuenioChanging(string value);
    partial void OnPermisoDuenioChanged();
    partial void OnSeguridadEntornoChanging(string value);
    partial void OnSeguridadEntornoChanged();
    partial void OnIntegrantesHogarChanging(string value);
    partial void OnIntegrantesHogarChanged();
    partial void OnAcuerdoFamiliarChanging(string value);
    partial void OnAcuerdoFamiliarChanged();
    partial void OnHayAlergiasChanging(string value);
    partial void OnHayAlergiasChanged();
    partial void OnOtrasMascotasChanging(string value);
    partial void OnOtrasMascotasChanged();
    partial void OnSociabilidadMascotasChanging(string value);
    partial void OnSociabilidadMascotasChanged();
    partial void OnHorasSoloChanging(string value);
    partial void OnHorasSoloChanged();
    partial void OnLugarDormirChanging(string value);
    partial void OnLugarDormirChanged();
    partial void OnPlanMudanzaChanging(string value);
    partial void OnPlanMudanzaChanged();
    partial void OnMotivoAdopcionChanging(string value);
    partial void OnMotivoAdopcionChanged();
    partial void OnAceptaGastosChanging(bool value);
    partial void OnAceptaGastosChanged();
    partial void OnAceptaCompromisoChanging(bool value);
    partial void OnAceptaCompromisoChanged();
    #endregion
		
		public SolicitudesAdopcionWS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_SolicitudWS", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id_SolicitudWS
		{
			get
			{
				return this._Id_SolicitudWS;
			}
			set
			{
				if ((this._Id_SolicitudWS != value))
				{
					this.OnId_SolicitudWSChanging(value);
					this.SendPropertyChanging();
					this._Id_SolicitudWS = value;
					this.SendPropertyChanged("Id_SolicitudWS");
					this.OnId_SolicitudWSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Usuario", DbType="Int NOT NULL")]
		public int Id_Usuario
		{
			get
			{
				return this._Id_Usuario;
			}
			set
			{
				if ((this._Id_Usuario != value))
				{
					this.OnId_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Id_Usuario = value;
					this.SendPropertyChanged("Id_Usuario");
					this.OnId_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Animal", DbType="Int NOT NULL")]
		public int Id_Animal
		{
			get
			{
				return this._Id_Animal;
			}
			set
			{
				if ((this._Id_Animal != value))
				{
					this.OnId_AnimalChanging(value);
					this.SendPropertyChanging();
					this._Id_Animal = value;
					this.SendPropertyChanged("Id_Animal");
					this.OnId_AnimalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaSolicitud", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaSolicitud
		{
			get
			{
				return this._FechaSolicitud;
			}
			set
			{
				if ((this._FechaSolicitud != value))
				{
					this.OnFechaSolicitudChanging(value);
					this.SendPropertyChanging();
					this._FechaSolicitud = value;
					this.SendPropertyChanged("FechaSolicitud");
					this.OnFechaSolicitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EdadSolicitante", DbType="Int")]
		public System.Nullable<int> EdadSolicitante
		{
			get
			{
				return this._EdadSolicitante;
			}
			set
			{
				if ((this._EdadSolicitante != value))
				{
					this.OnEdadSolicitanteChanging(value);
					this.SendPropertyChanging();
					this._EdadSolicitante = value;
					this.SendPropertyChanged("EdadSolicitante");
					this.OnEdadSolicitanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ocupacion", DbType="NVarChar(100)")]
		public string Ocupacion
		{
			get
			{
				return this._Ocupacion;
			}
			set
			{
				if ((this._Ocupacion != value))
				{
					this.OnOcupacionChanging(value);
					this.SendPropertyChanging();
					this._Ocupacion = value;
					this.SendPropertyChanged("Ocupacion");
					this.OnOcupacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DireccionCompleta", DbType="NVarChar(500)")]
		public string DireccionCompleta
		{
			get
			{
				return this._DireccionCompleta;
			}
			set
			{
				if ((this._DireccionCompleta != value))
				{
					this.OnDireccionCompletaChanging(value);
					this.SendPropertyChanging();
					this._DireccionCompleta = value;
					this.SendPropertyChanged("DireccionCompleta");
					this.OnDireccionCompletaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NVarChar(20)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RedesSociales", DbType="NVarChar(255)")]
		public string RedesSociales
		{
			get
			{
				return this._RedesSociales;
			}
			set
			{
				if ((this._RedesSociales != value))
				{
					this.OnRedesSocialesChanging(value);
					this.SendPropertyChanging();
					this._RedesSociales = value;
					this.SendPropertyChanged("RedesSociales");
					this.OnRedesSocialesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoVivienda", DbType="NVarChar(50)")]
		public string TipoVivienda
		{
			get
			{
				return this._TipoVivienda;
			}
			set
			{
				if ((this._TipoVivienda != value))
				{
					this.OnTipoViviendaChanging(value);
					this.SendPropertyChanging();
					this._TipoVivienda = value;
					this.SendPropertyChanged("TipoVivienda");
					this.OnTipoViviendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenenciaInmueble", DbType="NVarChar(20)")]
		public string TenenciaInmueble
		{
			get
			{
				return this._TenenciaInmueble;
			}
			set
			{
				if ((this._TenenciaInmueble != value))
				{
					this.OnTenenciaInmuebleChanging(value);
					this.SendPropertyChanging();
					this._TenenciaInmueble = value;
					this.SendPropertyChanged("TenenciaInmueble");
					this.OnTenenciaInmuebleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermisoDuenio", DbType="NVarChar(50)")]
		public string PermisoDuenio
		{
			get
			{
				return this._PermisoDuenio;
			}
			set
			{
				if ((this._PermisoDuenio != value))
				{
					this.OnPermisoDuenioChanging(value);
					this.SendPropertyChanging();
					this._PermisoDuenio = value;
					this.SendPropertyChanged("PermisoDuenio");
					this.OnPermisoDuenioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeguridadEntorno", DbType="NVarChar(1000)")]
		public string SeguridadEntorno
		{
			get
			{
				return this._SeguridadEntorno;
			}
			set
			{
				if ((this._SeguridadEntorno != value))
				{
					this.OnSeguridadEntornoChanging(value);
					this.SendPropertyChanging();
					this._SeguridadEntorno = value;
					this.SendPropertyChanged("SeguridadEntorno");
					this.OnSeguridadEntornoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntegrantesHogar", DbType="NVarChar(255)")]
		public string IntegrantesHogar
		{
			get
			{
				return this._IntegrantesHogar;
			}
			set
			{
				if ((this._IntegrantesHogar != value))
				{
					this.OnIntegrantesHogarChanging(value);
					this.SendPropertyChanging();
					this._IntegrantesHogar = value;
					this.SendPropertyChanged("IntegrantesHogar");
					this.OnIntegrantesHogarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AcuerdoFamiliar", DbType="NVarChar(20)")]
		public string AcuerdoFamiliar
		{
			get
			{
				return this._AcuerdoFamiliar;
			}
			set
			{
				if ((this._AcuerdoFamiliar != value))
				{
					this.OnAcuerdoFamiliarChanging(value);
					this.SendPropertyChanging();
					this._AcuerdoFamiliar = value;
					this.SendPropertyChanged("AcuerdoFamiliar");
					this.OnAcuerdoFamiliarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HayAlergias", DbType="NVarChar(10)")]
		public string HayAlergias
		{
			get
			{
				return this._HayAlergias;
			}
			set
			{
				if ((this._HayAlergias != value))
				{
					this.OnHayAlergiasChanging(value);
					this.SendPropertyChanging();
					this._HayAlergias = value;
					this.SendPropertyChanged("HayAlergias");
					this.OnHayAlergiasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtrasMascotas", DbType="NVarChar(1000)")]
		public string OtrasMascotas
		{
			get
			{
				return this._OtrasMascotas;
			}
			set
			{
				if ((this._OtrasMascotas != value))
				{
					this.OnOtrasMascotasChanging(value);
					this.SendPropertyChanging();
					this._OtrasMascotas = value;
					this.SendPropertyChanged("OtrasMascotas");
					this.OnOtrasMascotasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SociabilidadMascotas", DbType="NVarChar(1000)")]
		public string SociabilidadMascotas
		{
			get
			{
				return this._SociabilidadMascotas;
			}
			set
			{
				if ((this._SociabilidadMascotas != value))
				{
					this.OnSociabilidadMascotasChanging(value);
					this.SendPropertyChanging();
					this._SociabilidadMascotas = value;
					this.SendPropertyChanged("SociabilidadMascotas");
					this.OnSociabilidadMascotasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HorasSolo", DbType="NVarChar(50)")]
		public string HorasSolo
		{
			get
			{
				return this._HorasSolo;
			}
			set
			{
				if ((this._HorasSolo != value))
				{
					this.OnHorasSoloChanging(value);
					this.SendPropertyChanging();
					this._HorasSolo = value;
					this.SendPropertyChanged("HorasSolo");
					this.OnHorasSoloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LugarDormir", DbType="NVarChar(255)")]
		public string LugarDormir
		{
			get
			{
				return this._LugarDormir;
			}
			set
			{
				if ((this._LugarDormir != value))
				{
					this.OnLugarDormirChanging(value);
					this.SendPropertyChanging();
					this._LugarDormir = value;
					this.SendPropertyChanged("LugarDormir");
					this.OnLugarDormirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanMudanza", DbType="NVarChar(1000)")]
		public string PlanMudanza
		{
			get
			{
				return this._PlanMudanza;
			}
			set
			{
				if ((this._PlanMudanza != value))
				{
					this.OnPlanMudanzaChanging(value);
					this.SendPropertyChanging();
					this._PlanMudanza = value;
					this.SendPropertyChanged("PlanMudanza");
					this.OnPlanMudanzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotivoAdopcion", DbType="NVarChar(1000)")]
		public string MotivoAdopcion
		{
			get
			{
				return this._MotivoAdopcion;
			}
			set
			{
				if ((this._MotivoAdopcion != value))
				{
					this.OnMotivoAdopcionChanging(value);
					this.SendPropertyChanging();
					this._MotivoAdopcion = value;
					this.SendPropertyChanged("MotivoAdopcion");
					this.OnMotivoAdopcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AceptaGastos", DbType="Bit NOT NULL")]
		public bool AceptaGastos
		{
			get
			{
				return this._AceptaGastos;
			}
			set
			{
				if ((this._AceptaGastos != value))
				{
					this.OnAceptaGastosChanging(value);
					this.SendPropertyChanging();
					this._AceptaGastos = value;
					this.SendPropertyChanged("AceptaGastos");
					this.OnAceptaGastosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AceptaCompromiso", DbType="Bit NOT NULL")]
		public bool AceptaCompromiso
		{
			get
			{
				return this._AceptaCompromiso;
			}
			set
			{
				if ((this._AceptaCompromiso != value))
				{
					this.OnAceptaCompromisoChanging(value);
					this.SendPropertyChanging();
					this._AceptaCompromiso = value;
					this.SendPropertyChanged("AceptaCompromiso");
					this.OnAceptaCompromisoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
