#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adopcion_Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Adopcion")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAnimales(Animales instance);
    partial void UpdateAnimales(Animales instance);
    partial void DeleteAnimales(Animales instance);
    partial void InsertSolicitud_Adopcion(Solicitud_Adopcion instance);
    partial void UpdateSolicitud_Adopcion(Solicitud_Adopcion instance);
    partial void DeleteSolicitud_Adopcion(Solicitud_Adopcion instance);
    partial void InsertRefugio(Refugio instance);
    partial void UpdateRefugio(Refugio instance);
    partial void DeleteRefugio(Refugio instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Adopcion_Data.Properties.Settings.Default.AdopcionConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Animales> Animales
		{
			get
			{
				return this.GetTable<Animales>();
			}
		}
		
		public System.Data.Linq.Table<Solicitud_Adopcion> Solicitud_Adopcion
		{
			get
			{
				return this.GetTable<Solicitud_Adopcion>();
			}
		}
		
		public System.Data.Linq.Table<Refugio> Refugio
		{
			get
			{
				return this.GetTable<Refugio>();
			}
		}
		
		public System.Data.Linq.Table<User> User
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Animales")]
	public partial class Animales : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Animal;
		
		private string _Nombre;
		
		private string _Especie;
		
		private int _Id_Refugio;
		
		private string _Descripcion;
		
		private System.DateTime _Fecha;
		
		private string _Genero;
		
		private string _Edad;
		
		private string _Imagen;
		
		private string _Tamano;
		
		private string _Personalidad;
		
		private EntitySet<Solicitud_Adopcion> _Solicitud_Adopcion;
		
		private EntityRef<Refugio> _Refugio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_AnimalChanging(int value);
    partial void OnId_AnimalChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnEspecieChanging(string value);
    partial void OnEspecieChanged();
    partial void OnId_RefugioChanging(int value);
    partial void OnId_RefugioChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    partial void OnGeneroChanging(string value);
    partial void OnGeneroChanged();
    partial void OnEdadChanging(string value);
    partial void OnEdadChanged();
    partial void OnImagenChanging(string value);
    partial void OnImagenChanged();
    partial void OnTamanoChanging(string value);
    partial void OnTamanoChanged();
    partial void OnPersonalidadChanging(string value);
    partial void OnPersonalidadChanged();
    #endregion
		
		public Animales()
		{
			this._Solicitud_Adopcion = new EntitySet<Solicitud_Adopcion>(new Action<Solicitud_Adopcion>(this.attach_Solicitud_Adopcion), new Action<Solicitud_Adopcion>(this.detach_Solicitud_Adopcion));
			this._Refugio = default(EntityRef<Refugio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Animal", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Animal
		{
			get
			{
				return this._Id_Animal;
			}
			set
			{
				if ((this._Id_Animal != value))
				{
					this.OnId_AnimalChanging(value);
					this.SendPropertyChanging();
					this._Id_Animal = value;
					this.SendPropertyChanged("Id_Animal");
					this.OnId_AnimalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Especie", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Especie
		{
			get
			{
				return this._Especie;
			}
			set
			{
				if ((this._Especie != value))
				{
					this.OnEspecieChanging(value);
					this.SendPropertyChanging();
					this._Especie = value;
					this.SendPropertyChanged("Especie");
					this.OnEspecieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Refugio", DbType="Int NOT NULL")]
		public int Id_Refugio
		{
			get
			{
				return this._Id_Refugio;
			}
			set
			{
				if ((this._Id_Refugio != value))
				{
					if (this._Refugio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_RefugioChanging(value);
					this.SendPropertyChanging();
					this._Id_Refugio = value;
					this.SendPropertyChanged("Id_Refugio");
					this.OnId_RefugioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Genero", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Genero
		{
			get
			{
				return this._Genero;
			}
			set
			{
				if ((this._Genero != value))
				{
					this.OnGeneroChanging(value);
					this.SendPropertyChanging();
					this._Genero = value;
					this.SendPropertyChanged("Genero");
					this.OnGeneroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Edad
		{
			get
			{
				return this._Edad;
			}
			set
			{
				if ((this._Edad != value))
				{
					this.OnEdadChanging(value);
					this.SendPropertyChanging();
					this._Edad = value;
					this.SendPropertyChanged("Edad");
					this.OnEdadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imagen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Imagen
		{
			get
			{
				return this._Imagen;
			}
			set
			{
				if ((this._Imagen != value))
				{
					this.OnImagenChanging(value);
					this.SendPropertyChanging();
					this._Imagen = value;
					this.SendPropertyChanged("Imagen");
					this.OnImagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tamano", DbType="NVarChar(50)")]
		public string Tamano
		{
			get
			{
				return this._Tamano;
			}
			set
			{
				if ((this._Tamano != value))
				{
					this.OnTamanoChanging(value);
					this.SendPropertyChanging();
					this._Tamano = value;
					this.SendPropertyChanged("Tamano");
					this.OnTamanoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Personalidad", DbType="NVarChar(50)")]
		public string Personalidad
		{
			get
			{
				return this._Personalidad;
			}
			set
			{
				if ((this._Personalidad != value))
				{
					this.OnPersonalidadChanging(value);
					this.SendPropertyChanging();
					this._Personalidad = value;
					this.SendPropertyChanged("Personalidad");
					this.OnPersonalidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Animales_Solicitud_Adopcion", Storage="_Solicitud_Adopcion", ThisKey="Id_Animal", OtherKey="Id_Animal")]
		public EntitySet<Solicitud_Adopcion> Solicitud_Adopcion
		{
			get
			{
				return this._Solicitud_Adopcion;
			}
			set
			{
				this._Solicitud_Adopcion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Refugio_Animales", Storage="_Refugio", ThisKey="Id_Refugio", OtherKey="Id_Refugio", IsForeignKey=true)]
		public Refugio Refugio
		{
			get
			{
				return this._Refugio.Entity;
			}
			set
			{
				Refugio previousValue = this._Refugio.Entity;
				if (((previousValue != value) 
							|| (this._Refugio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Refugio.Entity = null;
						previousValue.Animales.Remove(this);
					}
					this._Refugio.Entity = value;
					if ((value != null))
					{
						value.Animales.Add(this);
						this._Id_Refugio = value.Id_Refugio;
					}
					else
					{
						this._Id_Refugio = default(int);
					}
					this.SendPropertyChanged("Refugio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Solicitud_Adopcion(Solicitud_Adopcion entity)
		{
			this.SendPropertyChanging();
			entity.Animales = this;
		}
		
		private void detach_Solicitud_Adopcion(Solicitud_Adopcion entity)
		{
			this.SendPropertyChanging();
			entity.Animales = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Solicitud_Adopcion")]
	public partial class Solicitud_Adopcion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Solicitud;
		
		private int _Id_Usuario;
		
		private int _Id_Animal;
		
		private string _Situacion;
		
		private System.DateTime _Fecha;
		
		private string _Folio;
		
		private EntityRef<Animales> _Animales;
		
		private EntityRef<User> _User;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_SolicitudChanging(int value);
    partial void OnId_SolicitudChanged();
    partial void OnId_UsuarioChanging(int value);
    partial void OnId_UsuarioChanged();
    partial void OnId_AnimalChanging(int value);
    partial void OnId_AnimalChanged();
    partial void OnSituacionChanging(string value);
    partial void OnSituacionChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    partial void OnFolioChanging(string value);
    partial void OnFolioChanged();
    #endregion
		
		public Solicitud_Adopcion()
		{
			this._Animales = default(EntityRef<Animales>);
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Solicitud", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Solicitud
		{
			get
			{
				return this._Id_Solicitud;
			}
			set
			{
				if ((this._Id_Solicitud != value))
				{
					this.OnId_SolicitudChanging(value);
					this.SendPropertyChanging();
					this._Id_Solicitud = value;
					this.SendPropertyChanged("Id_Solicitud");
					this.OnId_SolicitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Usuario", DbType="Int NOT NULL")]
		public int Id_Usuario
		{
			get
			{
				return this._Id_Usuario;
			}
			set
			{
				if ((this._Id_Usuario != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Id_Usuario = value;
					this.SendPropertyChanged("Id_Usuario");
					this.OnId_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Animal", DbType="Int NOT NULL")]
		public int Id_Animal
		{
			get
			{
				return this._Id_Animal;
			}
			set
			{
				if ((this._Id_Animal != value))
				{
					if (this._Animales.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_AnimalChanging(value);
					this.SendPropertyChanging();
					this._Id_Animal = value;
					this.SendPropertyChanged("Id_Animal");
					this.OnId_AnimalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Situacion", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Situacion
		{
			get
			{
				return this._Situacion;
			}
			set
			{
				if ((this._Situacion != value))
				{
					this.OnSituacionChanging(value);
					this.SendPropertyChanging();
					this._Situacion = value;
					this.SendPropertyChanged("Situacion");
					this.OnSituacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Folio", DbType="NVarChar(50)")]
		public string Folio
		{
			get
			{
				return this._Folio;
			}
			set
			{
				if ((this._Folio != value))
				{
					this.OnFolioChanging(value);
					this.SendPropertyChanging();
					this._Folio = value;
					this.SendPropertyChanged("Folio");
					this.OnFolioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Animales_Solicitud_Adopcion", Storage="_Animales", ThisKey="Id_Animal", OtherKey="Id_Animal", IsForeignKey=true)]
		public Animales Animales
		{
			get
			{
				return this._Animales.Entity;
			}
			set
			{
				Animales previousValue = this._Animales.Entity;
				if (((previousValue != value) 
							|| (this._Animales.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Animales.Entity = null;
						previousValue.Solicitud_Adopcion.Remove(this);
					}
					this._Animales.Entity = value;
					if ((value != null))
					{
						value.Solicitud_Adopcion.Add(this);
						this._Id_Animal = value.Id_Animal;
					}
					else
					{
						this._Id_Animal = default(int);
					}
					this.SendPropertyChanged("Animales");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Solicitud_Adopcion", Storage="_User", ThisKey="Id_Usuario", OtherKey="Id_Usuario", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.Solicitud_Adopcion.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.Solicitud_Adopcion.Add(this);
						this._Id_Usuario = value.Id_Usuario;
					}
					else
					{
						this._Id_Usuario = default(int);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Refugio")]
	public partial class Refugio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Refugio;
		
		private string _Nombre;
		
		private string _Direccion;
		
		private string _Estado;
		
		private System.DateTime _Fecha;
		
		private string _Ref;
		
		private EntitySet<Animales> _Animales;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_RefugioChanging(int value);
    partial void OnId_RefugioChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    partial void OnRefChanging(string value);
    partial void OnRefChanged();
    #endregion
		
		public Refugio()
		{
			this._Animales = new EntitySet<Animales>(new Action<Animales>(this.attach_Animales), new Action<Animales>(this.detach_Animales));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Refugio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Refugio
		{
			get
			{
				return this._Id_Refugio;
			}
			set
			{
				if ((this._Id_Refugio != value))
				{
					this.OnId_RefugioChanging(value);
					this.SendPropertyChanging();
					this._Id_Refugio = value;
					this.SendPropertyChanged("Id_Refugio");
					this.OnId_RefugioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ref", DbType="NVarChar(50)")]
		public string Ref
		{
			get
			{
				return this._Ref;
			}
			set
			{
				if ((this._Ref != value))
				{
					this.OnRefChanging(value);
					this.SendPropertyChanging();
					this._Ref = value;
					this.SendPropertyChanged("Ref");
					this.OnRefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Refugio_Animales", Storage="_Animales", ThisKey="Id_Refugio", OtherKey="Id_Refugio")]
		public EntitySet<Animales> Animales
		{
			get
			{
				return this._Animales;
			}
			set
			{
				this._Animales.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Animales(Animales entity)
		{
			this.SendPropertyChanging();
			entity.Refugio = this;
		}
		
		private void detach_Animales(Animales entity)
		{
			this.SendPropertyChanging();
			entity.Refugio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Usuario;
		
		private string _Username;
		
		private string _Nombre;
		
		private string _Apellido_Pat;
		
		private string _Apellido_Mat;
		
		private string _Telefono;
		
		private string _Correo;
		
		private string _RFC;
		
		private string _password;
		
		private int _tipo;
		
		private System.DateTime _Fecha;
		
		private string _Ref;
		
		private EntitySet<Solicitud_Adopcion> _Solicitud_Adopcion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_UsuarioChanging(int value);
    partial void OnId_UsuarioChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellido_PatChanging(string value);
    partial void OnApellido_PatChanged();
    partial void OnApellido_MatChanging(string value);
    partial void OnApellido_MatChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnRFCChanging(string value);
    partial void OnRFCChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OntipoChanging(int value);
    partial void OntipoChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    partial void OnRefChanging(string value);
    partial void OnRefChanged();
    #endregion
		
		public User()
		{
			this._Solicitud_Adopcion = new EntitySet<Solicitud_Adopcion>(new Action<Solicitud_Adopcion>(this.attach_Solicitud_Adopcion), new Action<Solicitud_Adopcion>(this.detach_Solicitud_Adopcion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Usuario
		{
			get
			{
				return this._Id_Usuario;
			}
			set
			{
				if ((this._Id_Usuario != value))
				{
					this.OnId_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Id_Usuario = value;
					this.SendPropertyChanged("Id_Usuario");
					this.OnId_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido_Pat", DbType="NVarChar(50)")]
		public string Apellido_Pat
		{
			get
			{
				return this._Apellido_Pat;
			}
			set
			{
				if ((this._Apellido_Pat != value))
				{
					this.OnApellido_PatChanging(value);
					this.SendPropertyChanging();
					this._Apellido_Pat = value;
					this.SendPropertyChanged("Apellido_Pat");
					this.OnApellido_PatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido_Mat", DbType="NVarChar(50)")]
		public string Apellido_Mat
		{
			get
			{
				return this._Apellido_Mat;
			}
			set
			{
				if ((this._Apellido_Mat != value))
				{
					this.OnApellido_MatChanging(value);
					this.SendPropertyChanging();
					this._Apellido_Mat = value;
					this.SendPropertyChanged("Apellido_Mat");
					this.OnApellido_MatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NVarChar(15)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFC", DbType="NVarChar(13)")]
		public string RFC
		{
			get
			{
				return this._RFC;
			}
			set
			{
				if ((this._RFC != value))
				{
					this.OnRFCChanging(value);
					this.SendPropertyChanging();
					this._RFC = value;
					this.SendPropertyChanged("RFC");
					this.OnRFCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="Int NOT NULL")]
		public int tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ref", DbType="NVarChar(50)")]
		public string Ref
		{
			get
			{
				return this._Ref;
			}
			set
			{
				if ((this._Ref != value))
				{
					this.OnRefChanging(value);
					this.SendPropertyChanging();
					this._Ref = value;
					this.SendPropertyChanged("Ref");
					this.OnRefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Solicitud_Adopcion", Storage="_Solicitud_Adopcion", ThisKey="Id_Usuario", OtherKey="Id_Usuario")]
		public EntitySet<Solicitud_Adopcion> Solicitud_Adopcion
		{
			get
			{
				return this._Solicitud_Adopcion;
			}
			set
			{
				this._Solicitud_Adopcion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Solicitud_Adopcion(Solicitud_Adopcion entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_Solicitud_Adopcion(Solicitud_Adopcion entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
}
#pragma warning restore 1591
